Allow to select an existing security to replace a newly imported one
portfolio-performance/portfolio pull request #3494
Opened 2023-08-09 14:43 UTC by buchen

When reviewing the newly created items, the user can choose to replace a new security with an existing security. All transactions are then imported and added to the existing security.

* Extended ExtractedEntry with security dependency (= if an extracted entry depends on another extracted security) and security override (= if the user chose to replace the imported security with an existing security)
* Refactored the import logic into ImportController to allow sharing between PDF and CSV imports

https://github.com/portfolio-performance/portfolio/assets/587976/70d37082-d2f7-4d27-932a-2601c63f0a11

2023-08-09 16:08 UTC, Nirus2000 requested changes

2023-08-09 16:08 UTC, Nirus2000 commented on name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/wizards/datatransfer/ImportController.java
> +        }
```suggestion
        var isDirty = false;
        for (ReviewExtractedItemsPage page : pages)
        {
            page.afterPage();
            var isPageDirty = importPage(page, newSecurities);
            isDirty |= isPageDirty;
        }
```

2023-08-09 16:09 UTC, Nirus2000 commented
This is very nice... i :heart_on_fire: it...

2023-08-09 17:49 UTC, buchen commented on name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/wizards/datatransfer/ExtractedEntry.java
> +                                        || (maxCode == Status.Code.WARNING && item.isInvestmentPlanItem()));
It was only a formatting change - maybe I should remove even the formatting from the commit.

I am also not sure if the statements are identical due to the missing parenthesis.

2023-08-09 17:50 UTC, merged

2023-08-11 14:59 UTC, siprbaum commented
On a technical level, I understand what the feature can do, but I am struggling a little for which use cases I would use it.

Would this be helpful e.g. when a security was merged/replaced by another?
E.g. in the past, the Lyxor MSCI World (WKN: ETF110) was merged/replaced by Amundi MSCI World (WKN: ETF018).
The bank automatically exchanged the existing ETF110 in the depot with Amundi ETF018 shares.

Any pointer to existing uses cases/documentation when to use this feature would be appreciated.