CSVAccountTransactionExtractor: Do not blindly ignore amount sign
portfolio-performance/portfolio pull request #3617
Opened 2023-10-29 11:28 UTC by pfalcon

CSV importer's existing mental model is that each transaction would be explicitly categorized (via a "type" column) as Buy or Sell. It then just ignores the sign of transaction amount (by calling Math.abs()).

This assumption is not realistic to cover all the cases. Another way is to have a generic "security transaction" type, and the sign of the amount signifies the actual operation, e.g. negative for Buy, positive for Sell.

This change allows to handle such CSV statements, by "inverting" the configured transaction type. For example, if given type column value is mapped to "BUY", but amount is negative, it is turned into "SELL".

2023-10-29 11:29 UTC, pfalcon commented
This addressed p.2 from https://github.com/portfolio-performance/portfolio/issues/3616

2023-10-30 10:17 UTC, buchen requested changes
Hi @pfalcon,

thanks for the pull request. I like the change. It will give some more flexibility.

The build failure is due to code formatting of the new change (curly braces). Can you be so kind and format it with the default formatter in Eclipse (Ctrl-F)?

I think we should add a **test case** to [CSVAccountTransactionExtractorTest](https://github.com/portfolio-performance/portfolio/blob/master/name.abuchen.portfolio.tests/src/name/abuchen/portfolio/datatransfer/csv/CSVAccountTransactionExtractorTest.java) that tests the new behavior. Otherwise it is too easy to accidentally break this new feature with a future commit. Can you be so kind and add one?

Finally, I believe we should have the same logic when importing "only" portfolio transactions: [CSVPortfolioTransactionExtractor.java#L243-L249](https://github.com/portfolio-performance/portfolio/blob/master/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/csv/CSVPortfolioTransactionExtractor.java#L243-L249)

Thanks for taking the time for a contribution to Portfolio Performance.

Andreas.

2023-10-30 16:44 UTC, Nirus2000 commented
I have my doubts here that this is a good idea....

Several problems will arise here.
1) If the sale value of the shares is less than the fees. (Sale with negative amount)
2.) Hereby cancellations are made possible of purchase and sale and not removed. The transactions are posted or duplicated at the wrong time. (Purchase or sale cancellation from day X).
3.) The same applies to reverse transactions of deliveries and removals.

2023-10-31 07:29 UTC, buchen commented
@Nirus2000 writes:
> Several problems will arise here.

Let's recap what this change enables.

Let's say we have a CSV of this format:
```csv
date;type;amount
2023-10-31;Ein-/Auszahlung;2000
2023-11-01;Ein-/Auszahlung;-1000
```

In this case, the type cannot be used to determine the transaction - the sign of the value is needed as well.
The sign of the amount can be used to make it a DEPOSIT or REMOVAL (= withdrawal).
In this case, one can import the CSV as a 2000 EUR deposit and 1000 EUR removal.
The imported transactions does not carry the sign anymore, of course, as all internal values must be positive in the model of Portfolio Performance.

If I understand your concerns, they are about negative values in the internal transactions model of Portfolio Performance. At the moment, I do not see this change allowing the negative values to leak in.

2023-10-31 07:52 UTC, pfalcon commented
```
date;type;amount
2023-10-31;Ein-/Auszahlung;2000
2023-11-01;Ein-/Auszahlung;-1000
```

Yes, this exemplifies a case we see here. I understand that it may change behavior for some users of CSV import, so it would depend on benefits it brings vs possible corner cases, and IMHO benefits outweigh. All in all, I posted it for feedback. I'll try to address review comments as time permits. (I otherwise have a whole bunch of changes in my fork, some adhoc, all without tests, but some certainly may be useful to other people, and to make PP a more generic tool (== cover more usecases), which should be a good aim for an open-source project.)

2025-07-28 00:27 UTC, flywire commented
> I otherwise have a whole bunch of changes in my fork

"_This PR is hosed by now and should be reworked_." It's unfortunate simple ideas are so hard to propose with Git.

2026-03-07 09:59 UTC, aanno commented
This would at least be possible, see my PR draft https://github.com/portfolio-performance/portfolio/pull/5445

2026-05-25 19:04 UTC, Nirus2000 commented
Closing this PR due to inactivity.
The change itself was well-received — thanks again to @pfalcon for the contribution. However, the review requests from @buchen (code formatting fix to resolve the build failure, a test case in CSVAccountTransactionExtractorTest, and applying the same sign-inversion logic to CSVPortfolioTransactionExtractor) have not been addressed since the last activity in late 2023.
If anyone wants to pick this up, the approach is sound. A new PR with the three open points resolved should have a good chance of being merged. The relevant discussion and the linked issue #3616 provide all necessary context.

2026-05-25 19:04 UTC, closed without merging