RenaultBank Importer Fix for 2020 Kontoauszug
portfolio-performance/portfolio pull request #3745
Opened 2024-01-17 12:41 UTC by ZfT2

Bugfix für einen 2020er Kontoauszug, der sich aktuell nicht importieren lässt, da das Währungssymbl "EUR" hier leider nicht sauber vorkommt.

2024-01-20 08:24 UTC, Nirus2000 requested changes

2024-01-24 17:36 UTC, Nirus2000 commented
Hello @ZfT2 
Would you please be so kind as to validate the `currency` here as well as in the [AKF PDF Importer](https://github.com/portfolio-performance/portfolio/pull/3764#issuecomment-1906357230)?

Please have a look [here](https://github.com/portfolio-performance/portfolio/blob/master/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/DkbPDFExtractor.java#L685:L711) + [here](https://github.com/portfolio-performance/portfolio/blob/master/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/DkbPDFExtractor.java#L724) and implement it in your source.

Regards
Alex

2024-01-25 19:52 UTC, buchen commented
@Nirus2000 writes:

>  Would you please be so kind as to validate the currency here...?

Looking at the importer, I am not sure what you mean by **validate**. The code samples you link to, extract the currency in the document context, and apply it, but do not seem to have validation logic. You mean checking that it is actually three letters after remove the unnecessary underscores (_) and spaces?

2024-01-25 19:54 UTC, buchen commented
Okay, I guess you mean the call to ```asCurrencyCode(...)``` call, right?

2024-01-28 19:54 UTC, buchen commented
I have added the asCurrencyUnit call, squashed and merged the pull request.

2024-01-28 19:54 UTC, closed without merging