new PDF Importer for J&T Direktbank
portfolio-performance/portfolio pull request #3748
Opened 2024-01-17 14:46 UTC by ZfT2

support  J&T Direktbank Tagesgeldkonto-Auszüge

2024-01-17 15:26 UTC, Nirus2000 commented on name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/JTDirektbankPDFExtractor.java
> +    private static final String CONTEXT_VALUE_TRUE = "true";
Hello @ZfT2 
thx... is it possible for you to adapt the [regular expression to our standard](https://github.com/portfolio-performance/portfolio/blob/master/CONTRIBUTING.md#regular-expressions)?

2024-01-17 15:32 UTC, Nirus2000 commented on name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/JTDirektbankPDFExtractor.java
> +        addBankIdentifier("500 150 01");
Hello @ZfT2 
We cannot use a bank code for addBankIdentifier(). As soon as a user has this bank code, errors are generated.
Please use another one.
Also I don't see any test case which uses this addBankIdentifier().

Please remove it.

2024-01-17 15:36 UTC, Nirus2000 requested changes
Hey @ZfT2 , 
thanks for the contributions. 
It generally looks good to me. 
Have a look at the review comments I added.

2024-01-17 15:43 UTC, Nirus2000 requested changes

2024-01-17 15:43 UTC, Nirus2000 commented on name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/JTDirektbankPDFExtractor.java
> +    private static final String CONTEXT_VALUE_TRUE = "true";
Hello @ZfT2
thx... is it possible for you to adapt the [regular expression to our standard](https://github.com/portfolio-performance/portfolio/blob/master/CONTRIBUTING.md#regular-expressions)?

```suggestion
    private static final String DEPOSIT_2023 = "^(?<date>[\\d]{2}\\.[\\d]{2}\\.) [\\d]{2}\\.[\\d]{2}\\. (.*gutschr\\.?)[\\s]{1,}(?<amount>[\\.,\\d]+) [H]";
    private static final String REMOVAL_2023 = "^(?<date>[\\d]{2}\\.[\\d]{2}\\.) [\\d]{2}\\.[\\d]{2}\\. (.berweisungsauftrag)[\\s]{1,}(?<amount>[\\.,\\d]+) [S]";
    private static final String INTEREST_2023 = "^(?<date>[\\d]{2}\\.[\\d]{2}\\.) [\\d]{2}\\.[\\d]{2}\\. (Abschluss lt\\. Anlage \\d)[\\s]{1,}(?<amount>[\\.,\\d]+).*";

    private static final String CONTEXT_KEY_YEAR = "year";
    private static final String CONTEXT_KEY_CURRENCY = "currency";
    private static final String CONTEXT_KEY_TRANSACTIONS_HAVE_FULL_DATE = "transactions_full_date";
    private static final String CONTEXT_VALUE_TRUE = "true";
```

2024-01-17 15:43 UTC, Nirus2000 commented on name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/JTDirektbankPDFExtractor.java
> +            contextProviderCommon(context, lines, yearPattern, currencyPattern);
```suggestion
            Pattern yearPattern = Pattern.compile(".*Kontoauszug Nr\\.)[\\s]{1,}[\\d+]\\/(?<year>[\\d]{4})");
            Pattern currencyPattern = Pattern
                            .compile("(?<currency>[\\w]{3})\\-Konto Kontonummer.*");
            contextProviderCommon(context, lines, yearPattern, currencyPattern);
```

2024-01-18 07:22 UTC, Nirus2000 requested changes

2024-01-18 07:22 UTC, Nirus2000 commented on name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/JTDirektbankPDFExtractor.java
> +                            .compile("(?<currency>[\\w]{3})\\-Konto Kontonummer.*");
Sorry, my fault. Here is the correct regex. 👍🏻 
```suggestion
            Pattern yearPattern = Pattern.compile("^.*Kontoauszug Nr\\.[\\s]{1,}[\\d]{1,2}\/(?<year>[\\d]{4})$");
            Pattern currencyPattern = Pattern.compile("^(?<currency>[\w]{3})\-Konto Kontonummer.*$");
```

2024-01-18 13:19 UTC, ZfT2 commented
no problem, thanks for reviewing it :)

2024-01-20 08:48 UTC, merged