New PDF Importer for Bank11
portfolio-performance/portfolio pull request #3784
Opened 2024-02-09 13:00 UTC by ZfT2

2024-02-09 15:21 UTC, Nirus2000 requested changes

2024-02-09 15:21 UTC, Nirus2000 commented on name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/Bank11PDFExtractor.java
> +    }
Hello @ZfT2 
1.)
I think you keep making the same mistake...

2.)
You dont need the BiConsumer.... again....

3.)
You dont need `Map<String, String> context = type.getCurrentContext();`

add follow like -> [here](https://github.com/portfolio-performance/portfolio/blob/master/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/DkbPDFExtractor.java#L723:L738) <-

`.documentContext("currency", "year") //`

then you can simply use `v.get("currency")` or `v.get("year")` to retrieve the string, as it is already parsed in the document.

2024-02-09 15:51 UTC, ZfT2 commented
Sorry... hope it is now resolved correctly.

2024-02-10 19:35 UTC, Nirus2000 commented
Perfect 🥇

2024-02-15 20:11 UTC, buchen commented
Whenever @Nirus2000 says 'perfect', I just merge it. Thanks @ZfT2

2024-02-15 20:11 UTC, merged