Add column with graphical price range widget
portfolio-performance/portfolio pull request #4274
Opened 2024-10-05 21:23 UTC by pfalcon

This PR builds on ParameterizedColumnLabelProvider introduced in https://github.com/portfolio-performance/portfolio/pull/4225, add to it owner-draw capabilities, as discussed in https://github.com/portfolio-performance/portfolio/issues/4226, and implements on top of it column which represent security price range within given (configurable) time interval in a graphical form, where full range is represented by a horizontal bar, and a notch on it shows current *relative* position. That's how almost every stock analysis site shows price ranges, and what IMHO was sorely missed in PP. This new column type is expected to supersede "Distance from ATH" column, issues with which are:

* "ATH" is so 2021, where's "ATL"?
* Showing distance in absolute terms doesn't make much sense. For example, if some bond ETF had ATH at 60, and currently at 59, it may seem it's barely off the top, but if its ATL over this time is 58, it's actually half way thru its range.

2024-10-05 21:25 UTC, pfalcon commented
Screenshot:
![Screenshot at 2024-10-05 23-31-27](https://github.com/user-attachments/assets/cf5579cd-c328-48c2-a0e9-4a66b015cda0)

2024-10-12 07:00 UTC, buchen requested changes
Very nice feature.

I made some (minor) comments. What do you think?

2024-10-13 15:12 UTC, pfalcon commented on name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/util/viewers/ParameterizedColumnLabelProvider.java
> +public class ParameterizedColumnLabelProvider extends ColumnLabelProvider implements Listener
Well, that's why I recorded my thinking and its progress over time in #4224, #4226 - I started with the idea to implement a kind of "mixin", and even succeeded in that, as much as Java allows that, but then thought that it's unneeded complication and merged everything into a single class. If you think that the right balance for PP is to have a separate class for owner-draw, while inheriting from ParameterizedColumnLabelProvider, I'll look into refactoring it like you suggest.

2024-10-13 15:14 UTC, pfalcon commented on name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/columns/RangeWidgetColumn.java
> +                Values.Date.format(range.getHighDate())); //$NON-NLS-1$
> Actually, Eclipse should show a warning in the "Problems" view.

As I mentioned, I don't really use Eclipse, just my generic text editor, so just rely on "mvn verify" to catch the obvious goofs for me. Will fix.

2024-10-13 15:32 UTC, pfalcon commented on name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/columns/RangeWidgetColumn.java
> +            event.gc.fillRectangle(event.x, event.y + yOff, width, BAR_HEIGHT);
> I propose not to paint the background here at all.
> Two reasons: first, the selection marker will be gone. Second, depending on the platform there are alternating background of the table rows which will also be gone.

Hmm, that's not what I tried to implement (per the docs), and not what I see here on Linux/GTK. First of all, owner-draw support for table cell consists of handling 3 events: MeasureItem, EraseItem, PaintItem. First 2 have default implementation on SWT level, and we rely on that. EraseItem is where things like backgrounds and selection are handled, and what I did is non-overridable implementation like:

```
+                // We're saying that we'll draw actual things ("foreground")
+                // ourselves. Things like background, selection, etc. will
+                // still be handled by SWT.
+                event.detail &= ~SWT.FOREGROUND;
```

That's all per https://www.eclipse.org/articles/Article-CustomDrawingTableAndTreeItems/customDraw.htm

Now, the actual widget consists of : a bar (rectangle), on which a notch (a line) is drawn. Both the bar and notch have their own colors, and that's what we draw. The bar is in particular drawn with top and bottom paddings from the actual cell size, exactly to make selection visible even in this column. Again, it all works as expected in GTK+ (well, I don't have an alternating table rows theme but would hope it works, as the selection does).

![Screenshot at 2024-10-13 22-17-33](https://github.com/user-attachments/assets/3f1ecaf7-f597-439a-81bd-419dc49b9d8b)

So, I wonder if that's one of those unfortunate platform-specific discrepancies in SWT. I'll try to research more as time permits.

2024-10-13 15:32 UTC, pfalcon commented on name.abuchen.portfolio/src/name/abuchen/portfolio/math/AllTimeHigh.java
> +        Long range = athValue - atlValue;
Will fix

2024-10-13 15:57 UTC, pfalcon commented on name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/columns/RangeWidgetColumn.java
> +            var range = valueProvider.apply(event.item.getData(), option);
Well, there're definitely a lot of optimizations to do in PP in various places. For example, functional-like streaming interface to calculate stuff is nice and expressive (most of the time), but making 2 passes to calculate 2 values over the same items is clearly less efficient than ol' good loop calculating everything at once and possibly terminating early.

But optimizing prematurely also complicates things a lot, so it makes sense to have separate passes at that, hopefully driven by real quantified criteria. In that regard, I didn't really see noticeable slowdown with the widget enabled, even with pretty large (*) instrument lists. (I actually would think that SWT table widget uses virtual model approach and creates Items only for currently visible model rows, though I'm not really sure that's the case).

(*) Going for optimization efforts, we'd need some good reference to compare/measure things on, e.g. a list of S&P500 constituents, or something.

2024-10-13 15:57 UTC, pfalcon commented on name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/columns/RangeWidgetColumn.java
> +            Double v1 = valueProvider.apply(o1, option).getRelLowDistance();
Will take care.

2024-10-18 08:57 UTC, buchen commented on name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/columns/RangeWidgetColumn.java
> +            event.gc.fillRectangle(event.x, event.y + yOff, width, BAR_HEIGHT);
At least on macOS, it looks fine (and as expected) if we do not paint the background

2024-10-18 08:58 UTC, buchen commented on name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/columns/RangeWidgetColumn.java
> +            event.gc.fillRectangle(event.x, event.y + yOff, width, BAR_HEIGHT);
But now I get what you want to achieve - you want a grey bar and on top that the indicator with the black bar. Maybe we need to do some padding (on some platforms)?

2024-10-18 09:00 UTC, buchen commented on name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/util/viewers/ParameterizedColumnLabelProvider.java
> +public class ParameterizedColumnLabelProvider extends ColumnLabelProvider implements Listener
Fair. it is a trade-off. In this particular case, I thought that the "enable" method is not necessary if I express my intention to use an owner draw by implementing a different class.

```java
public class ParameterizedOwnerDrawLabelProvider extends ParameterizedColumnLabelProvider implements Listener
{

    @Override
    protected void initialize(ColumnViewer viewer, ViewerColumn column)
    {
        super.initialize(viewer, column);

        var control = viewer.getControl();
        control.addListener(SWT.MeasureItem, this);
        control.addListener(SWT.EraseItem, this);
        control.addListener(SWT.PaintItem, this);
    }

    /**
     * Measure size of contents - optional to override.
     */
    public void measure(Event event)
    {
    }

    /**
     * Actually paint contents via event.gc, etc. Column is passed to
     * differentiate multiple columns with owner-draw contents.
     */
    public void paint(Event event)
    {
        PortfolioLog.error("paint() not implemented"); //$NON-NLS-1$
    }

    @Override
    public void handleEvent(Event event)
    {
        TableItem item = (TableItem) event.item;
        Table table = item.getParent();
        TableColumn tColumn = table.getColumn(event.index);
        if (tColumn != getTableColumn())
            return;

        switch (event.type)
        {
            case SWT.MeasureItem:
                this.measure(event);
                break;
            case SWT.PaintItem:
                this.paint(event);
                break;
            case SWT.EraseItem:
                // We're saying that we'll draw actual things ("foreground")
                // ourselves. Things like background, selection, etc. will
                // still be handled by SWT.
                event.detail &= ~SWT.FOREGROUND;
                break;
            default:
        }
    }
}
```

2024-10-27 07:49 UTC, pfalcon commented
@buchen : I pushed new patch version which implements most of the suggestion you had (they marked as resolved). I also updated tooltip format a bit to show numeric relative percentages from high/low (so people could check for actual ATH/ATL reliably).

What's left is the matter of painting body of the horizontal scale bar. Can you please make a screenshot of how it looks for you on MacOS to understand better why you think it needs changing?

2024-11-29 07:36 UTC, pfalcon commented
@buchen : Any update on this?

2024-12-29 17:23 UTC, buchen commented
Merged.

I added a couple of things:
* Removed the background rectangle (does not fit to alternative table
  row coloring)
* Use color depending on the theme (light, dark)
* Added the missing translations
* Renamed column for consistency (widgets are used on the dashboard)

2024-12-29 17:23 UTC, closed without merging

2024-12-30 13:34 UTC, pfalcon commented
@buchen:
 
Thanks! Happy New Year!

If you went with renaming, I wonder if you have any ideas about AllTimeHigh.java, as it's no longer literally such. I'm not sure what better name would fit though. HighLowCalc.java?