Add Color Definitions to ColorSchema Enum
portfolio-performance/portfolio pull request #4283
Opened 2024-10-12 14:27 UTC by Nirus2000

1. **GREEN_YELLOW_RED**: Green for gains, Red for losses, Yellow for neutral values.
2. **GREEN_WHITE_RED**: Green for gains, White for neutral, Red for losses.
3. **GREEN_RED_GREY**: Green for gains, Red for losses, Grey for neutral.
4. **BLUE_ORANGE_GREY**: Blue for stable values, Orange for volatile values, Grey for neutral.
5. **BLACK_YELLOW_WHITE**: Black for extreme gains, Yellow for moderate returns, White for neutral.

The colors are obtained from colors.java

---------------
Hello @buchen 
I wanted to add the color orange to the colors blue and yellow in order to use them for the HeatMap color schemes. 

`public static final Color ORANGE = getColor(255, 165, 0); // FFA500`

Unfortunately, it keeps throwing me an error that I don't understand. It looks to me as if I cannot register the color orange.
Also, i don't find a test suite...

```
java.lang.NoClassDefFoundError: Could not initialize class name.abuchen.portfolio.ui.util.Colors
Could not initialize class name.abuchen.portfolio.ui.util.Colors
---------------------------------------
!ENTRY org.eclipse.e4.ui.workbench 4 0 2024-10-12 16:24:25.074
!MESSAGE Internal Error
!STACK 0
java.lang.NoClassDefFoundError: Could not initialize class name.abuchen.portfolio.ui.util.Colors
	at name.abuchen.portfolio.ui.editor.Sidebar.<init>(Sidebar.java:66)
	at name.abuchen.portfolio.ui.editor.ClientEditorSidebar.createSidebarControl(ClientEditorSidebar.java:89)
	at name.abuchen.portfolio.ui.editor.PortfolioPart.createContainerWithViews(PortfolioPart.java:160)
	at name.abuchen.portfolio.ui.editor.PortfolioPart.rebuildContainer(PortfolioPart.java:323)
	at name.abuchen.portfolio.ui.editor.PortfolioPart.onLoaded(PortfolioPart.java:354)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at name.abuchen.portfolio.ui.editor.ClientInput.setClient(ClientInput.java:678)
	at name.abuchen.portfolio.ui.editor.LoadClientThread.lambda$0(LoadClientThread.java:36)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4046)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3662)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:168)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "main"]
	at name.abuchen.portfolio.ui.util.Colors.getColor(Colors.java:192)
	at name.abuchen.portfolio.ui.util.Colors.<clinit>(Colors.java:132)
	at name.abuchen.portfolio.ui.theme.ThemeAddon.onThemeChanged(ThemeAddon.java:20)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4802)
	at org.eclipse.e4.ui.workbench.swt.DisplayUISynchronize.syncExec(DisplayUISynchronize.java:34)
	at org.eclipse.e4.ui.internal.di.UIEventObjectSupplier$UIEventHandler.handleEvent(UIEventObjectSupplier.java:64)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:208)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:206)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:133)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:75)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:44)
	at org.eclipse.e4.ui.css.swt.internal.theme.ThemeEngine.sendThemeChangeEvent(ThemeEngine.java:526)
	at org.eclipse.e4.ui.css.swt.internal.theme.ThemeEngine.setTheme(ThemeEngine.java:505)
	at org.eclipse.e4.ui.css.swt.internal.theme.ThemeEngine.setTheme(ThemeEngine.java:435)
	at org.eclipse.e4.ui.css.swt.internal.theme.ThemeEngine.setTheme(ThemeEngine.java:427)
	at name.abuchen.portfolio.ui.theme.CustomThemeEngine.restore(CustomThemeEngine.java:46)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.setCSSTheme(PartRenderingEngine.java:1417)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.initializeStyling(PartRenderingEngine.java:1324)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1050)
	... 17 more
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
```

2024-10-19 09:21 UTC, buchen requested changes
Hey @Nirus2000, thanks for enhancing the color palettes.

I am aware that green-red is not good enough because of color blindness and other reasons. Unfortunately, I also do not understand color theory good enough...

Besides the rather smaller comments in the code, I would help me if you can share the sites where you picked up the logic for the color palettes. I tried to search for schemas that are new to me (black - yellow), but could not really find material.

Andreas.

2024-10-19 09:21 UTC, buchen commented on name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/dashboard/heatmap/ColorSchema.java
> +                                : Colors.interpolate(Colors.WHITE.getRGB(), Colors.YELLOW.getRGB(), (float) p);
I have to admit, I do not understand the math. The 0.05 are deducted from the normalized 0 -> 1 range. As we normalize between -0.07 and +0.07, there are 0.14 on the range and 5% of that (the deduction) is 0.07.

Plus values that are above 0.07 will be black anyway (interpolation factor 1). As only performance > 0.05 is going into the black branch, the lower bound is 0.8571428571. The ```(p - 0.05) / 0.95)``` will rescale this to 0.8496240602. What difference does it make?


BTW, can you share where you picked up the black-yellow color palette? I looked for materials in the web, but was [not](https://www.datacamp.com/tutorial/seaborn-heatmaps) [really](https://vwo.com/blog/heatmap-colors/) [successful](https://www.atlassian.com/data/charts/how-to-choose-colors-data-visualization) in finding examples of black-yellow.

2024-10-19 09:25 UTC, buchen commented on name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/dashboard/heatmap/ColorSchema.java
> +                double p = normalizePerformance(performance);
Thinking about it some more, does it really make sense to normalize the performance here?

-0.07 will be normalized to 0, and +0.07 will be normalized to 1.
But then we interpolate depending on the original performance.
So dark gray/green will only be interpolated between 0 and 0.5.
And the gray/red will only be interpolated between 0.5 and 1.

2024-10-20 05:01 UTC, Nirus2000 commented on name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/dashboard/heatmap/ColorSchema.java
> +                                : Colors.interpolate(Colors.WHITE.getRGB(), Colors.RED.getRGB(), (float) p);
Done and updated the interpolate method to clamp the factor parameter between 0 and 1.

2024-10-20 05:02 UTC, Nirus2000 commented on name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/dashboard/heatmap/ColorSchema.java
> +            case GREEN_RED_GREY -> performance -> {
done

2024-10-20 05:14 UTC, Nirus2000 commented on name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/dashboard/heatmap/ColorSchema.java
> +                                : Colors.interpolate(Colors.GRAY.getRGB(), Colors.RED.getRGB(), (float) p);
We can add the following change
```
case GREEN_YELLOW_RED -> performance -> {
    double p = normalizePerformance(performance);
    float hue = (float) (p * 120); // 0 (red) bis 120 (green)

    // Increase intensity for the lower values
    if (p < 0.5) {
        hue *= 2;
    }
    
    return resourceManager.createColor(new RGB(hue, 0.9f, 1f));
};

2024-10-20 06:30 UTC, Nirus2000 commented
Hello @buchen 
I have implemented all your changes as best I could.

I have the following comments.
If we start with the `Colors.theme().defaultBackground().getRGB()`then the colors are interpolated in the DarkTheme, which means that the translations of the HeatMap color schemes are of course no longer correct. 
How do we want to solve this problem ❓ 🤔 

❓ It also remains to be seen whether we can define the heat maps more clearly than just using the color scheme. (see description below)
 
---

### Green-Yellow-Red:
This combination is often used to represent positive, neutral and negative performance.

### Green-White-Red:
This color scale is good for showing returns moving into a neutral zone.
When analyzing individual stocks, this heat map can help show investors how a stock has moved from neutral (white) to positive (green) and negative (red) returns. It is particularly useful if you want to differentiate between losses and gains.
[TradingView - Performance Heatmap](https://www.tradingview.com/script/bBPyKI9b-Stock-Market-Indices-Correlations-Heatmap/)

### Green-Gray-Red:
This chart is suitable for visualizing performance in the context of risk.
In a risk management dashboard, green boxes could represent stocks that combine high risk with positive performance, while red boxes represent high risk with poor performance. Gray fields could indicate neutral investments.
[finviz](https://finviz.com/map.ashx?st=w1)

### Blue-Gray-Orange:
This color scale is particularly useful for representing stable versus volatile assets.
In a currency market heat map, blue could represent stable currencies, while orange would represent volatile currencies. Gray boxes could represent a stable background, meaning that no significant movements have taken place.
[A1 - Trading](https://www.a1trading.com/currency-heatmap/)

### Yellow-White-Black:
This combination is useful to show moderate and extreme changes.
In a commodity price heat map, yellow could represent moderate price changes, while black shows extreme price fluctuations. This visualization helps traders prepare for potential market movements.

2024-10-25 14:44 UTC, closed without merging