fix italic and small font for "alt hint" in chart tooltip
portfolio-performance/portfolio pull request #4359
Opened 2024-11-18 19:29 UTC by mierin12

Closes https://github.com/portfolio-performance/portfolio/issues/4318

Hello, I do not know why, but this little change works on my Windows 11.
**Before :** 
![2024-11-18 20_27_30-Portfolio Performance](https://github.com/user-attachments/assets/db339db9-6bd2-4a08-9999-bbcbf727fefd)
 
**After :**
![2024-11-18 20_21_25-Portfolio Performance](https://github.com/user-attachments/assets/27e08e41-dc70-4981-89f3-61048334cff5)

2024-11-20 07:54 UTC, Nirus2000 commented
Hello @mierin12 
This also works for me under Windows10. Very good. 👍🏻 
![grafik](https://github.com/user-attachments/assets/000e7245-aa6b-4168-a18e-95096240b621)


---

However, I do have one comment. I have noticed that the translations are different.

**I have the following text in German translation:**
_'Alt' ('Option' unter macOS) beim Öffnen des Tooltips sortiert die Einträge nach Wert_

As far as I know, there should be a function for recognizing which operating system is being used.

2024-11-21 04:52 UTC, Nirus2000 commented
Perfect... 😉 👍🏻

2024-11-21 06:16 UTC, Nirus2000 commented on name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/util/chart/TimelineChartToolTip.java
> +        hint.setText(MessageFormat.format(Messages.TooltipHintPressAlt, pressAltOrOption));
hint.setText(MessageFormat.format(Messages.TooltipHintPressAlt, 
    Platform.OS_MACOSX.equals(Platform.getOS()) ? "Option" : "Alt"));

2024-11-21 09:51 UTC, Nirus2000 requested changes

2024-11-21 09:51 UTC, Nirus2000 commented on name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/util/chart/TimelineChartToolTip.java
> +
```suggestion
        hint.setText(MessageFormat.format(Messages.TooltipHintPressAlt, 
    Platform.OS_MACOSX.equals(Platform.getOS()) ? "Option" : "Alt"));
```

2024-11-21 19:53 UTC, mierin12 commented on name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/util/chart/TimelineChartToolTip.java
> +
Done with https://github.com/portfolio-performance/portfolio/pull/4359/commits/2b6be85a0c72f3db5cf35e2d2818a0803e131cda

2024-11-22 05:10 UTC, Nirus2000 approved these changes

2024-11-29 05:08 UTC, merged